ProjectITP/Models/ExamResult.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProjectITP.Models
{
    public class ExamResult
    {
        public int Id { get; set; }


        [Required]
        public int Grade { get; set; }
       
        
        [Display(Name ="URL")]
        public string Resultpdf { get; set; }


        
        
        public Subject Subject { get; set; }

        [Display(Name ="Enroolment Key")]
        public int SubjectId { get; set; }


    }
}

ProjectITP/Controllers/ExamResultsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.Reporting.WebForms;
using ProjectITP.Models;

namespace ProjectITP.Controllers
{
    [Authorize]
    public class ExamResultsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ExamResults
        public ActionResult Index()
        {
            var examResult = db.ExamResult.Include(e => e.Subject);
            

            if (User.IsInRole(RoleName.CanManageAll))
                return View(examResult.ToList());


            return View("IndexReadOnly", examResult.ToList());

        }

        // GET: ExamResults/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExamResult examResult = db.ExamResult.Find(id);
            if (examResult == null)
            {
                return HttpNotFound();
            }
            return View(examResult);
        }

        // GET: ExamResults/Create
        public ActionResult Create()
        {
            ViewBag.SubjectId = new SelectList(db.Subject, "id", "enrollmentKey");
            return View();
        }

        // POST: ExamResults/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Grade,Resultpdf,SubjectId")] ExamResult examResult , HttpPostedFileBase UploadFile)
        {
            if (ModelState.IsValid)
            {
                if (UploadFile != null)
                {

                    if (UploadFile.ContentType == "image/jpg" || UploadFile.ContentType == "image/png" ||
                        UploadFile.ContentType == "image/gif" || UploadFile.ContentType == "image/jpeg" ||
                        UploadFile.ContentType == "application/pdf")
                    {
                        UploadFile.SaveAs(Server.MapPath("/") + "/Images/" + UploadFile.FileName);
                        examResult.Resultpdf = UploadFile.FileName;
                    }
                    else
                    {
                        return View();
                    }

                }
                else
                {
                    return View();
                }







                db.ExamResult.Add(examResult);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SubjectId = new SelectList(db.Subject, "id", "enrollmentKey", examResult.SubjectId);
            return View(examResult);
        }

        // GET: ExamResults/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExamResult examResult = db.ExamResult.Find(id);
            if (examResult == null)
            {
                return HttpNotFound();
            }
            ViewBag.SubjectId = new SelectList(db.Subject, "id", "enrollmentKey", examResult.SubjectId);
            return View(examResult);
        }

        // POST: ExamResults/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Grade,Resultpdf,SubjectId")] ExamResult examResult, HttpPostedFileBase UploadFile)
        {
            if (ModelState.IsValid)
            {

                if (UploadFile != null)
                {

                    if (UploadFile.ContentType == "image/jpg" || UploadFile.ContentType == "image/png" ||
                        UploadFile.ContentType == "image/gif" || UploadFile.ContentType == "image/jpeg" ||
                        UploadFile.ContentType == "application/pdf")
                    {
                        UploadFile.SaveAs(Server.MapPath("/") + "/Images/" + UploadFile.FileName);
                        examResult.Resultpdf = UploadFile.FileName;
                    }
                    else
                    {
                        return View();
                    }

                }
                else
                {
                    return View();
                }






                db.Entry(examResult).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SubjectId = new SelectList(db.Subject, "id", "enrollmentKey", examResult.SubjectId);
            return View(examResult);
        }

        // GET: ExamResults/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExamResult examResult = db.ExamResult.Find(id);
            if (examResult == null)
            {
                return HttpNotFound();
            }
            return View(examResult);
        }

        // POST: ExamResults/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ExamResult examResult = db.ExamResult.Find(id);
            db.ExamResult.Remove(examResult);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        //Exam Result Report
        public ActionResult Reports(string ReportType)
        {

            var examsResuuls = db.ExamResult.Include(e => e.Subject);


            LocalReport localReport = new LocalReport();
            localReport.ReportPath = Server.MapPath("~/Reports/ExamResultReport.rdlc");

            ReportDataSource reportDataSource = new ReportDataSource();
            reportDataSource.Name = "ExamResultDataSet";
            reportDataSource.Value = examsResuuls.ToList();
            localReport.DataSources.Add(reportDataSource);
            string reportType = ReportType;
            string mimeType;
            string encoding;
            string fileNameExtension;

            if (reportType == "Excel")
            {
                fileNameExtension = "xlsx";
            }
            else if (reportType == "Word")
            {
                fileNameExtension = "docx";
            }
            else if (reportType == "Pdf")
            {
                fileNameExtension = "pdf";
            }
            else
            {
                fileNameExtension = "jpg";
            }


            string[] streams;
            Warning[] warnings;
            byte[] renderedByte;
            renderedByte = localReport.Render(reportType, "",
                out mimeType, out encoding, out fileNameExtension, out streams,
                out warnings);
            Response.AddHeader("content-disposition", "attachment;filename=ExamsResult_report." + fileNameExtension);
            return File(renderedByte, fileNameExtension);









        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjectITP/Views/ExamResults/Create.cshtml
@model ProjectITP.Models.ExamResult

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ExamResult</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Resultpdf, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="UploadFile" id="UploadFile" />
            </div>
            @Html.ValidationMessageFor(model => model.Resultpdf, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubjectId, "SubjectId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SubjectId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubjectId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "", new { @class = "btn btn-primary" })
</div>

ProjectITP/Views/ExamResults/Delete.cshtml
@model ProjectITP.Models.ExamResult

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ExamResult</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Subject.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Resultpdf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Resultpdf)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index", "", new { @class = "btn btn-primary" })
        </div>
    }
</div>

ProjectITP/Views/ExamResults/Details.cshtml
@model ProjectITP.Models.ExamResult

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>ExamResult</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Subject.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Resultpdf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Resultpdf)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id },  new { @class = "btn btn-success" }) |
    @Html.ActionLink("Back to List", "Index", "", new { @class = "btn btn-primary" })
</p>

ProjectITP/Views/ExamResults/Edit.cshtml
@model ProjectITP.Models.ExamResult

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ExamResult</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Resultpdf, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="UploadFile" id="UploadFile" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubjectId, "SubjectId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SubjectId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubjectId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "", new { @class = "btn btn-primary" })
</div>

ProjectITP/Views/ExamResults/Index.cshtml
@model IEnumerable<ProjectITP.Models.ExamResult>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="font-family:fantasy">Exam Result</h2>

<p>
    @Html.ActionLink("Create New", "Create", "ExamResults", new { @class = "btn btn-success" })
</p>


<hr />

@Html.ActionLink("Export To Excel", "Reports", new { ReportType = "Excel" }, new { @class = "btn btn-primary" }) |
@Html.ActionLink("Export To Pdf", "Reports", new { ReportType = "Pdf" }, new { @class = "btn btn-primary" }) |
@Html.ActionLink("Export To word", "Reports", new { ReportType = "Word" }, new { @class = "btn btn-primary" }) |
@Html.ActionLink("Export To Image", "Reports", new { ReportType = "Image" }, new { @class = "btn btn-primary" }) |

<hr />

<table id="ExamResult" class="table table-hover table-bordered">
    <thead>
        <tr class="bg-primary">
            <th>
                @Html.DisplayNameFor(model => model.Subject.enrollmentKey)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Grade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Resultpdf)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Subject.enrollmentKey)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Grade)
                </td>
                <td>
                    <a href="~/Images/@item.Resultpdf">@Html.DisplayFor(modelItem => item.Resultpdf)</a>
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-primary" }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-info" }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }
    </tbody>
</table>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


    <script>
        $(document).ready(function () {
            var table = $("#ExamResult").DataTable();

        });
    </script>


}

ProjectITP/Views/ExamResults/IndexReadOnly.cshtml
@model IEnumerable<ProjectITP.Models.ExamResult>

@{
    ViewBag.Title = "Index";

}

<h2 style="font-family:fantasy">Exam Result</h2>


<table id="ExamResult" class="table table-hover table-bordered">
    <thead>
        <tr class="bg-primary">
            <th>
                @Html.DisplayNameFor(model => model.Subject.enrollmentKey)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Grade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Resultpdf)
            </th>

        </tr>
    </thead>

    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Subject.enrollmentKey)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Grade)
                </td>
                <td>
                    <a href="~/Images/@item.Resultpdf">@Html.DisplayFor(modelItem => item.Resultpdf)</a>
                </td>

            </tr>
        }

    </tbody>

</table>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


    <script>
        $(document).ready(function () {
            var table = $("#ExamResult").DataTable();

        });
    </script>


}