ProjectITP/Models/Subject.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProjectITP.Models
{
    public class Subject
    {
        public int id { get; set; }
        [Required]
        [StringLength(255)]
        [Display(Name = "Subject Name")]
        [RegularExpression("^[A-Za-z]*$", ErrorMessage = "Only Strings are allowed")]
        public string  name { get; set; }

        [Required]
        [Display(Name = "Enrollment Key")]
        [RegularExpression("^[0-9]*$", ErrorMessage ="Only numbers allowed")]
        public int enrollmentKey { get; set; }

        [Required]
        [Display(Name = "Grade")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Only Numbers allowed")]
        public int grade { get; set; }


                public SubjectCategory SubjectCategory { get; set; }
 

        [Display(Name ="Type")]
                public int SubjectCategoryId { get; set; }

              


        public ApplicationUser ApplicationUser { get; set; }

        [Display(Name ="Teacher ID")]
        public int ApplicationUserId { get; set; }
        

    }
}

ProjectITP/Controllers/SubjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.Reporting.WebForms;
using ProjectITP.Models;

namespace ProjectITP.Controllers
{
    
    public class SubjectsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Subjects
        public ActionResult Index()
        {
            var subject = db.Subject.Include(s => s.SubjectCategory).Include(u => u.ApplicationUser);
            

            if (User.IsInRole(RoleName.CanManageAll))
                return View(subject.ToList());


            return View("IndexReadOnly",subject.ToList());

        }


        //Subject Report

        public ActionResult Reports(string ReportType)
        {

            var subjects = db.Subject.Include(s => s.SubjectCategory).Include(u => u.ApplicationUser);


            LocalReport localReport = new LocalReport();
            localReport.ReportPath = Server.MapPath("~/Reports/SubjectReport.rdlc");

            ReportDataSource reportDataSource = new ReportDataSource();
            reportDataSource.Name = "SubjectDataSet";
            reportDataSource.Value = subjects.ToList();
            localReport.DataSources.Add(reportDataSource);
            string reportType = ReportType;
            string mimeType;
            string encoding;
            string fileNameExtension;

            if (reportType == "Excel")
            {
                fileNameExtension = "xlsx";
            }
            else if (reportType == "Word")
            {
                fileNameExtension = "docx";
            }
            else if (reportType == "Pdf")
            {
                fileNameExtension = "pdf";
            }
            else
            {
                fileNameExtension = "jpg";
            }


            string[] streams;
            Warning[] warnings;
            byte[] renderedByte;
            renderedByte = localReport.Render(reportType, "",
                out mimeType, out encoding, out fileNameExtension, out streams,
                out warnings);
            Response.AddHeader("content-disposition", "attachment;filename=Subject_report." + fileNameExtension);
            return File(renderedByte, fileNameExtension);









        }




        // GET: Subjects/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject subject = db.Subject.Find(id);
            if (subject == null)
            {
                return HttpNotFound();
            }
            return View(subject);
        }

        // GET: Subjects/Create
        //when click the create button loadin the create form
        public ActionResult Create()
        {
            ViewBag.SubjectCategoryId = new SelectList(db.SubjectCategories, "Id", "Type");
            ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "Id");
            return View();
        }

        // POST: Subjects/Create
        //to send the data to the database
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,enrollmentKey,grade,SubjectCategoryId,ApplicationUserId")] Subject subject)
        {
            if (ModelState.IsValid)
            {
                db.Subject.Add(subject);
                db.SaveChanges();
                return RedirectToAction("Index");
            }


            ViewBag.SubjectCategoryId = new SelectList(db.SubjectCategories, "Id", "Type");
            ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "Id");

            return View(subject);
        }

        // GET: Subjects/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject subject = db.Subject.Find(id);
            if (subject == null)
            {
                return HttpNotFound();
            }
            ViewBag.SubjectCategoryId = new SelectList(db.SubjectCategories, "Id", "Type");
            ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "Id");
            return View(subject);
        }

        // POST: Subjects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,enrollmentKey,grade,SubjectCategoryId,ApplicationUserId")] Subject subject)
        {
            if (ModelState.IsValid)
            {
                db.Entry(subject).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SubjectCategoryId = new SelectList(db.SubjectCategories, "Id", "Type");
            ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "Id");

            return View(subject);
        }

        // GET: Subjects/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject subject = db.Subject.Find(id);
            if (subject == null)
            {
                return HttpNotFound();
            }
            return View(subject);
        }

        // POST: Subjects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Subject subject = db.Subject.Find(id);
            db.Subject.Remove(subject);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }






    }
}

ProjectITP/Views/Subjects/Create.cshtml
@model ProjectITP.Models.Subject

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Subject</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.enrollmentKey, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.enrollmentKey, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.enrollmentKey, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.grade, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.grade, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.grade, "", new { @class = "text-danger" })
        </div>
    </div>


    @*

        <div class="form-group">
            @Html.LabelFor(model => model.teacher, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.teacher, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.teacher, "", new { @class = "text-danger" })
            </div>
        </div>

    *@


    <div class="form-group">
        @Html.LabelFor(model => model.SubjectCategory.Id, "SubjectCategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("SubjectCategoryId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.SubjectCategoryId, "", new { @class = "text-danger" })
        </div>
    </div>




    <div class="form-group">
        @Html.LabelFor(model => model.ApplicationUser.Id, "ApplicationUserId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ApplicationUserId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ApplicationUserId, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "", new { @class = "btn btn-primary" })
</div>

ProjectITP/Views/Subjects/Delete.cshtml
@model ProjectITP.Models.Subject

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Subject</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.enrollmentKey)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.enrollmentKey)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.grade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.grade)
        </dd>

        

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index", "", new { @class = "btn btn-primary" })
        </div>
    }
</div>

ProjectITP/Views/Subjects/Details.cshtml
@model ProjectITP.Models.Subject

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Subject</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.enrollmentKey)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.enrollmentKey)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.grade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.grade)
        </dd>

       

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id },  new { @class = "btn btn-success" }) |
    @Html.ActionLink("Back to List", "Index", "", new { @class = "btn btn-primary" })
</p>

ProjectITP/Views/Subjects/Edit.cshtml
@model ProjectITP.Models.Subject

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Subject</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.id)

    <div class="form-group">
        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.enrollmentKey, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.enrollmentKey, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.enrollmentKey, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.grade, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.grade, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.grade, "", new { @class = "text-danger" })
        </div>
    </div>

    @* <div class="form-group">
            @Html.LabelFor(model => model.teacher, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.teacher, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.teacher, "", new { @class = "text-danger" })
            </div>
        </div>
    *@

    <div class="form-group">
        @Html.LabelFor(model => model.ApplicationUserId, "ApplicationUserId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ApplicationUserId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ApplicationUserId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SubjectCategoryId, "SubjectCategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("SubjectCategoryId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.SubjectCategoryId, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "", new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjectITP/Views/Subjects/Index.cshtml
@model IEnumerable<ProjectITP.Models.Subject>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="font-family:fantasy">Subjects</h2>


@Html.ActionLink("Create New", "Create", "Subjects", new { @class = "btn btn-success" })



<hr />

@Html.ActionLink("Export To Excel", "Reports", new { ReportType = "Excel" }, new { @class = "btn btn-primary" }) |
@Html.ActionLink("Export To Pdf", "Reports", new { ReportType = "Pdf" }, new { @class = "btn btn-primary" }) |
@Html.ActionLink("Export To word", "Reports", new { ReportType = "Word" }, new { @class = "btn btn-primary" }) |
@Html.ActionLink("Export To Image", "Reports", new { ReportType = "Image" }, new { @class = "btn btn-primary" }) |

<hr />



<table id="subjects" class="table table-hover table-bordered">


    <thead >
        <tr class="bg-primary">
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.enrollmentKey)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.grade)
            </th>
            <th>
                Teacher's Name
            </th>
            <th>
                Subject Category
            </th>
            <th>
                Teacher's Id
            </th>
            <th></th>
        </tr>


    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.enrollmentKey)

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.grade)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ApplicationUser.Name)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.SubjectCategory.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ApplicationUser.Id)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.id }, new { @class = "btn btn-primary" }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.id }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }
    </tbody>
</table>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


    <script>
        $(document).ready(function () {
            var table = $("#subjects").DataTable();

        });
    </script>


}

ProjectITP/Views/Subjects/IndexReadOnly.cshtml
@model IEnumerable<ProjectITP.Models.Subject>

@{
    ViewBag.Title = "Index";

}




<br />
<br />



<h1 style="font-family:fantasy">Scholarship</h1>

<hr />



<table id="subjects" class="table table-hover table-bordered">


    <thead>
        <tr class="bg-primary">
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.enrollmentKey)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.grade)
            </th>
            <th>
                Teacher's Name
            </th>


        </tr>


    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            if (item.SubjectCategory.Id == 1)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.enrollmentKey)

                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.grade)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ApplicationUser.Name)
                    </td>




                </tr>
            }
        }
    </tbody>
</table>


<hr />

<h1 style="font-family:fantasy">Ordinary Level</h1>

<hr />


<table id="subjects1" class="table table-hover table-bordered">


    <thead>
        <tr class="bg-primary">
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.enrollmentKey)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.grade)
            </th>
            <th>
                Teacher's Name
            </th>


        </tr>


    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            if (item.SubjectCategory.Id == 2)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.enrollmentKey)

                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.grade)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ApplicationUser.Name)
                    </td>




                </tr>
            }
        }
    </tbody>
</table>



<hr />

<h1 style="font-family:fantasy">Advance Level</h1>

<hr />


<table id="subjects2" class="table table-hover table-bordered">


    <thead>
        <tr class="bg-primary">
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.enrollmentKey)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.grade)
            </th>
            <th>
                Teacher's Name
            </th>


        </tr>


    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            if (item.SubjectCategory.Id == 3)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.enrollmentKey)

                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.grade)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ApplicationUser.Name)
                    </td>




                </tr>
            }
        }
    </tbody>
</table>



<hr />

<h1 style="font-family:fantasy">Others</h1>

<hr />


<table id="subjects3" class="table table-hover table-bordered">


    <thead>
        <tr class="bg-primary">
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.enrollmentKey)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.grade)
            </th>
            <th>
                Teacher's Name
            </th>


        </tr>


    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            if (item.SubjectCategory.Id == 4)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.enrollmentKey)

                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.grade)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ApplicationUser.Name)
                    </td>




                </tr>
            }
        }
    </tbody>
</table>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


    <script>
        $(document).ready(function () {
            var table = $("#subjects").DataTable();
            var table = $("#subjects1").DataTable();
            var table = $("#subjects2").DataTable();
            var table = $("#subjects3").DataTable();

        });
    </script>


}