ProjectITP/Models/AcadamicUserPayment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProjectITP.Models
{
    public class AcadamicUserPayment
    {
        
        public int Id { get; set; }

        [Required]
        public int Year { get; set; }

        [Required]
        public int Month { get; set; }

        [Required]
        public double Payment { get; set; }

        [Required]
        [Display(Name ="Teacher Name")]
        public string TeacherName { get; set; }

        [Required]
        [Display(Name ="Teacher Id Number")]
        public int IdNumber { get; set; }



    }
}

ProjectITP/Controllers/AcadamicUserPaymentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.Reporting.WebForms;
using ProjectITP.Models;

namespace ProjectITP.Controllers
{
    public class AcadamicUserPaymentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: AcadamicUserPayments
        public ActionResult Index()
        {
            return View(db.acadamicUserPayments.ToList());
        }


        //Filter
        [HttpPost]
        public ActionResult Index(int? Year, int? Month)
        {

            var acadamicUserPayments = from emp in db.acadamicUserPayments select emp;

            if ((Year != null))
            {
                acadamicUserPayments = acadamicUserPayments.Where((e => e.Year == Year));
                acadamicUserPayments = acadamicUserPayments.Where(e => e.Month == Month);


            }

            return View(acadamicUserPayments);
        }





        // GET: AcadamicUserPayments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AcadamicUserPayment acadamicUserPayment = db.acadamicUserPayments.Find(id);
            if (acadamicUserPayment == null)
            {
                return HttpNotFound();
            }
            return View(acadamicUserPayment);
        }

        // GET: AcadamicUserPayments/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AcadamicUserPayments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Year,Month,Payment,TeacherName,IdNumber")] AcadamicUserPayment acadamicUserPayment)
        {
            if (ModelState.IsValid)
            {
                db.acadamicUserPayments.Add(acadamicUserPayment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(acadamicUserPayment);
        }

        // GET: AcadamicUserPayments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AcadamicUserPayment acadamicUserPayment = db.acadamicUserPayments.Find(id);
            if (acadamicUserPayment == null)
            {
                return HttpNotFound();
            }
            return View(acadamicUserPayment);
        }

        // POST: AcadamicUserPayments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Year,Month,Payment,TeacherName,IdNumber")] AcadamicUserPayment acadamicUserPayment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(acadamicUserPayment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(acadamicUserPayment);
        }

        // GET: AcadamicUserPayments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AcadamicUserPayment acadamicUserPayment = db.acadamicUserPayments.Find(id);
            if (acadamicUserPayment == null)
            {
                return HttpNotFound();
            }
            return View(acadamicUserPayment);
        }

        // POST: AcadamicUserPayments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AcadamicUserPayment acadamicUserPayment = db.acadamicUserPayments.Find(id);
            db.acadamicUserPayments.Remove(acadamicUserPayment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        //Report
        public ActionResult Reports(string ReportType)
        {

            var acadamicUserPayments = db.acadamicUserPayments;


            LocalReport localReport = new LocalReport();
            localReport.ReportPath = Server.MapPath("~/Reports/AcadamicPaymentReport.rdlc");

            ReportDataSource reportDataSource = new ReportDataSource();
            reportDataSource.Name = "AcadamicPaymentDataSet";
            reportDataSource.Value = acadamicUserPayments.ToList();
            localReport.DataSources.Add(reportDataSource);
            string reportType = ReportType;
            string mimeType;
            string encoding;
            string fileNameExtension;

            if (reportType == "Excel")
            {
                fileNameExtension = "xlsx";
            }
            else if (reportType == "Word")
            {
                fileNameExtension = "docx";
            }
            else if (reportType == "Pdf")
            {
                fileNameExtension = "pdf";
            }
            else
            {
                fileNameExtension = "jpg";
            }


            string[] streams;
            Warning[] warnings;
            byte[] renderedByte;
            renderedByte = localReport.Render(reportType, "",
                out mimeType, out encoding, out fileNameExtension, out streams,
                out warnings);
            Response.AddHeader("content-disposition", "attachment;filename=AcadamicUserPayment_report." + fileNameExtension);
            return File(renderedByte, fileNameExtension);









        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjectITP/Views/AcadamicUserPayments/Create.cshtml
@model ProjectITP.Models.AcadamicUserPayment

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AcadamicUserPayment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Month, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Month, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Month, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Payment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Payment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Payment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TeacherName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TeacherName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TeacherName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "", new { @class = "btn btn-primary" })
</div>

ProjectITP/Views/AcadamicUserPayments/Delete.cshtml
@model ProjectITP.Models.AcadamicUserPayment

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AcadamicUserPayment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Month)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Month)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Payment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Payment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TeacherName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TeacherName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdNumber)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index", "", new { @class = "btn btn-primary" })
        </div>
    }
</div>

ProjectITP/Views/AcadamicUserPayments/Details.cshtml
@model ProjectITP.Models.AcadamicUserPayment

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>AcadamicUserPayment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Month)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Month)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Payment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Payment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TeacherName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TeacherName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdNumber)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-success" }) |
    @Html.ActionLink("Back to List", "Index", "",new { @class = "btn btn-primary" })
</p>

ProjectITP/Views/AcadamicUserPayments/Edit.cshtml
@model ProjectITP.Models.AcadamicUserPayment

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AcadamicUserPayment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Month, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Month, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Month, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Payment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Payment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Payment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TeacherName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TeacherName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TeacherName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "", new { @class = "btn btn-primary" })
</div>

ProjectITP/Views/AcadamicUserPayments/Index.cshtml
@model IEnumerable<ProjectITP.Models.AcadamicUserPayment>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1 style="font-family:fantasy">Acadamic User Payments</h1>

<br />

@{
    double tot = 0;
}

<p>
    @Html.ActionLink("Create New", "Create", "AcadamicUserPayments", new { @class = "btn btn-success" })
</p>


<hr />

@Html.ActionLink("Export To Excel", "Reports", new { ReportType = "Excel" }, new { @class = "btn btn-primary" }) |
@Html.ActionLink("Export To Pdf", "Reports", new { ReportType = "Pdf" }, new { @class = "btn btn-primary" }) |
@Html.ActionLink("Export To word", "Reports", new { ReportType = "Word" }, new { @class = "btn btn-primary" }) |
@Html.ActionLink("Export To Image", "Reports", new { ReportType = "Image" }, new { @class = "btn btn-primary" }) |

<hr />


<hr />
<p>
    @using (Html.BeginForm())
    {
        <table>
            <tr class="bg-primary">
                <th>Year</th>
                <th>Month</th>
                <th>Check</th>
            </tr>
            <tr>
                <td> @Html.Editor("Year", new { htmlAttributes = new { @class = "form-control", Type = "integer" } })</td>
                <td> @Html.Editor("Month", new { htmlAttributes = new { @class = "form-control", Type = "integer" } })</td>
                <td><input type="submit" value="See Results" class="btn btn-default" /></td>
            </tr>
        </table>


    }
</p>

<hr />



<table id="acadamicPayment" class="table table-hover table-bordered ">
    <thead>
        <tr class="bg-primary" >
            <th>
                @Html.DisplayNameFor(model => model.Year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Month)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Payment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TeacherName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdNumber)
            </th>
            <th></th>
        </tr>

    </thead>

    <tbody>

        @foreach (var item in Model)
        {
            <tr  >
                <td>
                    @Html.DisplayFor(modelItem => item.Year)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Month)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Payment)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TeacherName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdNumber)
                </td>

                @{
                    tot = tot + item.Payment;
                }


                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id },  new { @class = "btn btn-primary" }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-info" }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }
    </tbody>
</table>


<table class="table">
    <tr>
        <th></th>
        <th></th>
        <th></th>
        <th>Total Price :</th>
        <th>Rs : @Html.DisplayFor(x => tot) </th>
    </tr>
</table>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


    <script>
        $(document).ready(function () {
            var table = $("#acadamicPayment").DataTable();

        });
    </script>


}