ProjectITP/Models/Profit.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProjectITP.Models
{
    public class Profit
    {

        public int Id { get; set; }

        [Required]
        public int Year { get; set; }

        [Required]
        public int Month { get; set; }

        [Required]
        [Display(Name ="Teacher's Payment")]
        public double TeacherPayment { get; set; }

        [Required]
        [Display(Name ="Non Acadamic's Payment")]
        public double NonAcadamicPayment { get; set; }

        [Required]
        [Display(Name ="Utility Payment")]
        public double UtilityPayment { get; set; }

        [Required]
        [Display(Name ="Other Payment")]
        public double Others { get; set; }

        [Required]
        [Display(Name = "Monthly Income")]
        public double MonthlyIncome { get; set; }


    }
}

ProjectITP/Controllers/ProfitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.Reporting.WebForms;
using ProjectITP.Models;

namespace ProjectITP.Controllers
{
    [Authorize]
    public class ProfitsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Profits
        public ActionResult Index()
        {
            return View(db.profits.ToList());
        }




        //filter
        [HttpPost]
       public ActionResult Index(int? Year, int? Month)
        {

            var profits1 = from emp in db.profits select emp;

            if ((Year != null))
            {
                profits1 = profits1.Where((e => e.Year == Year));
                profits1 = profits1.Where(e => e.Month == Month);


            }

            return View(profits1);
        }
        


        // GET: Profits/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Profit profit = db.profits.Find(id);
            if (profit == null)
            {
                return HttpNotFound();
            }
            return View(profit);
        }

        // GET: Profits/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Profits/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Year,Month,TeacherPayment,NonAcadamicPayment,UtilityPayment,Others,MonthlyIncome")] Profit profit)
        {
            if (ModelState.IsValid)
            {
                db.profits.Add(profit);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(profit);
        }

        // GET: Profits/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Profit profit = db.profits.Find(id);
            if (profit == null)
            {
                return HttpNotFound();
            }
            return View(profit);
        }

        // POST: Profits/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Year,Month,TeacherPayment,NonAcadamicPayment,UtilityPayment,Others,MonthlyIncome")] Profit profit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(profit).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(profit);
        }

        // GET: Profits/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Profit profit = db.profits.Find(id);
            if (profit == null)
            {
                return HttpNotFound();
            }
            return View(profit);
        }

        // POST: Profits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Profit profit = db.profits.Find(id);
            db.profits.Remove(profit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //Report
        public ActionResult Reports(string ReportType)
        {

            var profits = db.profits;


            LocalReport localReport = new LocalReport();
            localReport.ReportPath = Server.MapPath("~/Reports/ProfitReport.rdlc");

            ReportDataSource reportDataSource = new ReportDataSource();
            reportDataSource.Name = "ProfitDataSet";
            reportDataSource.Value = profits.ToList();
            localReport.DataSources.Add(reportDataSource);
            string reportType = ReportType;
            string mimeType;
            string encoding;
            string fileNameExtension;

            if (reportType == "Excel")
            {
                fileNameExtension = "xlsx";
            }
            else if (reportType == "Word")
            {
                fileNameExtension = "docx";
            }
            else if (reportType == "Pdf")
            {
                fileNameExtension = "pdf";
            }
            else
            {
                fileNameExtension = "jpg";
            }


            string[] streams;
            Warning[] warnings;
            byte[] renderedByte;
            renderedByte = localReport.Render(reportType, "",
                out mimeType, out encoding, out fileNameExtension, out streams,
                out warnings);
            Response.AddHeader("content-disposition", "attachment;filename=Profit_report." + fileNameExtension);
            return File(renderedByte, fileNameExtension);









        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjectITP/Views/Profits/Create.cshtml
@model ProjectITP.Models.Profit

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Profit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Month, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Month, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Month, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TeacherPayment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TeacherPayment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TeacherPayment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NonAcadamicPayment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NonAcadamicPayment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NonAcadamicPayment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UtilityPayment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UtilityPayment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UtilityPayment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Others, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Others, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Others, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MonthlyIncome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MonthlyIncome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MonthlyIncome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "", new { @class = "btn btn-primary" })
</div>

ProjectITP/Views/Profits/Delete.cshtml
@model ProjectITP.Models.Profit

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Profit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Month)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Month)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TeacherPayment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TeacherPayment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NonAcadamicPayment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NonAcadamicPayment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UtilityPayment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UtilityPayment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Others)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Others)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MonthlyIncome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MonthlyIncome)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index", "", new { @class = "btn btn-primary" })
        </div>
    }
</div>

ProjectITP/Views/Profits/Details.cshtml
@model ProjectITP.Models.Profit

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Profit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Month)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Month)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TeacherPayment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TeacherPayment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NonAcadamicPayment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NonAcadamicPayment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UtilityPayment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UtilityPayment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Others)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Others)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MonthlyIncome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MonthlyIncome)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id },  new { @class = "btn btn-success" }) |
    @Html.ActionLink("Back to List", "Index", "", new { @class = "btn btn-primary" })
</p>

ProjectITP/Views/Profits/Edit.cshtml
@model ProjectITP.Models.Profit

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Profit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Month, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Month, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Month, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TeacherPayment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TeacherPayment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TeacherPayment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NonAcadamicPayment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NonAcadamicPayment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NonAcadamicPayment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UtilityPayment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UtilityPayment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UtilityPayment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Others, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Others, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Others, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MonthlyIncome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MonthlyIncome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MonthlyIncome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "", new { @class = "btn btn-primary" })
</div>

ProjectITP/Views/Profits/Index.cshtml
@model IEnumerable<ProjectITP.Models.Profit>

@{
    /**/

    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="font-family:fantasy">Profits</h2>


@{
    double tot = 0;
}

<p>
    @Html.ActionLink("Create New", "Create" ,"Profits", new { @class = "btn btn-success" })
</p>


<hr />

@Html.ActionLink("Export To Excel", "Reports", new { ReportType = "Excel" }, new { @class = "btn btn-primary" }) |
@Html.ActionLink("Export To Pdf", "Reports", new { ReportType = "Pdf" }, new { @class = "btn btn-primary" }) |
@Html.ActionLink("Export To word", "Reports", new { ReportType = "Word" }, new { @class = "btn btn-primary" }) |
@Html.ActionLink("Export To Image", "Reports", new { ReportType = "Image" }, new { @class = "btn btn-primary" }) |

<hr />



<p>
    @using (Html.BeginForm())
    {
        <table>
            <tr  class="bg-primary">
                <th>Year</th> 
                <th>Month</th> 
                <th>Check</th>
            </tr>
            <tr>
                <td> @Html.Editor("Year", new { htmlAttributes = new { @class = "form-control", Type = "integer" } })</td> 
                <td> @Html.Editor("Month", new { htmlAttributes = new { @class = "form-control", Type = "integer" } })</td> 
                <td><input type="submit" value="See Results" class="btn btn-default" /></td>
            </tr>
        </table>

        
    }
</p>

<hr />



<table id="profit" class="table table-hover table-bordered">
    <thead>
        <tr  class="bg-primary">
            <th>
                @Html.DisplayNameFor(model => model.Year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Month)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TeacherPayment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NonAcadamicPayment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UtilityPayment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Others)
            </th>
            <th>
                Others
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Year)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Month)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TeacherPayment)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NonAcadamicPayment)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UtilityPayment)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Others)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MonthlyIncome)
                </td>


                @{
                    tot = tot + item.MonthlyIncome - item.TeacherPayment - item.NonAcadamicPayment - item.Others - item.UtilityPayment;
                }


                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-primary" }) 
                    @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-info" }) 
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }

    </tbody>
</table>




<table class="table">
    <tr>
        <th></th>
        <th></th>
        <th></th>
        <th>Total Profit :</th>
        <th>Rs : @Html.DisplayFor(x => tot) </th>
    </tr>
</table>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


    <script>
        $(document).ready(function () {
            var table = $("#profit").DataTable();

        });
    </script>


}